{%mainunit ../orca_scene2d.pas}

{**********************************************************************
 Package pl_ORCA.pkg
 This unit is extension part of Package pl_ORCA.pkg make by GoldenFox
 for CodeTyphon Studio  (http://www.pilotlogic.com/)
***********************************************************************}


{ TD2TGColumn }

function TD2TGColumn.CreateCellControl: TD2Control;
begin
  inherited;
end;
