{***************************************************
 ORCA 2D Library
 Copyright (C) PilotLogic Software House
 http://www.pilotlogic.com
 
 Package pl_ORCA.pkg
 This unit is part of CodeTyphon Studio
***********************************************************************}


{$ALIGN ON}
{$BOOLEVAL OFF}
{$LONGSTRINGS ON}
{$WRITEABLECONST ON}
{$WARNINGS OFF}
{$HINTS OFF}


{$B-} // Complete Boolean Evaluation
{$R-} // Range-Checking
{$V-} // Var-String Checking
{$T-} // Typed @ operator
{$X+} // Extended syntax
{$J+} // Enable writeable const




